// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

export const ADD_USER_CATEGORY_SUBSCRIPTION = 'ADD_USER_CATEGORY_SUBSCRIPTION'
export const DESTROY_USER_CATEGORY_SUBSCRIPTIONS = 'DESTROY_USER_CATEGORY_SUBSCRIPTIONS'
export const FETCH_USER_CATEGORY_SUBSCRIPTIONS = 'FETCH_USER_CATEGORY_SUBSCRIPTIONS'

export const ADD_USER_USER_SUBSCRIPTION = 'ADD_USER_USER_SUBSCRIPTION'
export const DESTROY_USER_USER_SUBSCRIPTIONS = 'DESTROY_USER_USER_SUBSCRIPTIONS'
export const FETCH_USER_USER_SUBSCRIPTIONS = 'FETCH_USER_USER_SUBSCRIPTIONS'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'
