// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

export const ADD_SUBSCRIPTION = 'ADD_SUBSCRIPTION'
export const DESTROY_SUBSCRIPTIONS = 'DESTROY_SUBSCRIPTIONS'
export const FETCH_SUBSCRIPTIONS = 'FETCH_SUBSCRIPTIONS'
export const CHANGE_SUBSCRIPTION_FIELD = 'CHANGE_SUBSCRIPTION_FIELD'


// lang.js
export const SET_LOCALE = 'SET_LOCALE'
